# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/login
Accept: application/json

{
  "email": "arifogluisa@gmail.com",
  "password": "testing321"
}
###
